repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.3
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
